### ISSUE TITLE
[Visiteur]A propos

### ISSUE THREAD

**Issue by achrefsoltani** [achrefsoltani/Trituxchatbot#1]
**_Tâches développeur :_** 

- [x] Api : Créer l'api de récupération des choix

- [x] Front : Affiche le choix de l'utilisateur dans le chatbot .

- [x] Front : Afficher les réponses et les choix suivants dans le chatbot .

**_Description:_**

En tant que Visiteur, je voudrais être en mesure d'interagir avec le chatbot afin de pouvoir avoir une idée sur le Groupe Tritux et comment le contacter.

_**Pré-conditions:**_ 

Les choix sont déja crées.
On a choisi "A propos"

_**Post-conditions:**_ 

Affichage des choix et réponses.

**_Règles métiers:_**  

| Attribut  | Importance  | Règle  | Priorité  |
| ------------- | ------------- |  ------------- |  ------------- | 

**_Boutons d'action:_** 

| Bouton | Evènement | Allez vers | Dépendance |
| --- | --- | --- | --- |
| Tritux | Selectionner le choix "Tritux" | Rester sur la même page | Afficher le choix "contact" |
| Contact | Selectionner le choix "Contact" | Rester sur la même page | --- |
| Objectifs | Selectionner le choix "Objectif" | Rester sur la même page | --- |
| Valeurs | Selectionner le choix "Valeurs" | Rester sur la même page | --- |
| Engagement | Selectionner le choix "Engagement" | Rester sur la même page | --- |
| Retour au menu | Retourner au menu principale | Rester sur la même page | --- |
| icon "Retour" | Retourner à la liste de choix precédente | Rester sur la même page | --- |

_**Critères d’acceptation:**_ 

Scénario : .

Étant donné que je suis au menu principale,
Lorsque je clique sur "A propos" ,
Alors le système affiche 4 choix : "Tritux", "Objectifs", "Valeurs", "Engagements" . Chaque choix conduit à un ensemble d'informations **(Mockup 1-2-4-5-6)**
 
***
(Suite)

Étant donné que j'ai déja choisis "Tritux",
Lorsque je clique "Contact",
Alors le système affiche les coordonnées du groupe Tritux.  **(Mockup 3)**

> **_Mock up 1_**
![A propos](https://user-images.githubusercontent.com/60237898/154443236-0e2441fe-16f3-405d-bdf3-8c2c51945b03.png)

> **_Mock up 2_**
![A propos - Tritux](https://user-images.githubusercontent.com/60237898/154443449-a0226b15-ed9f-42b8-99a9-633fa653a73b.png)

> **_Mock up 3_**
![A propos - Tritux - Contact](https://user-images.githubusercontent.com/60237898/154443496-84809ead-48fd-4467-b659-549507b322e8.png)

> **_Mock up 4_**
![A propos - Objectifs](https://user-images.githubusercontent.com/60237898/154443522-6387c0c5-6a66-44a4-8522-9f3f34fde6d4.png)

> **_Mock up 5_**
![A propos - Valeurs](https://user-images.githubusercontent.com/60237898/154443542-533a8c06-735f-4c55-8133-c645fa4b32f6.png)

> **_Mock up 6_**
![A propos - Engagements](https://user-images.githubusercontent.com/60237898/154443574-6c297ed5-cffe-4cde-9f74-7b9a64871998.png)
