### ISSUE TITLE
[Visiteur]Services

### ISSUE THREAD

**Issue by achrefsoltani** [achrefsoltani/Trituxchatbot#2]
**_Tâches développeur :_** 

- [x] Api : Créer l'api de récupération des choix

- [x] Front : Affiche le choix de l'utilisateur dans le chatbot .

- [x] Front : Afficher les réponses et les choix suivants dans le chatbot .

**_Description:_**

En tant que Visiteur, je voudrais être en mesure d'interagir avec le chatbot afin de pouvoir avoir une idée sur les services du Groupe Tritux.

_**Pré-conditions:**_ 

Les choix sont déja crées.
On a choisi "Services"

_**Post-conditions:**_ 

Affichage des choix et réponses.

**_Règles métiers:_**  

| Attribut  | Importance  | Règle  | Priorité  |
| ------------- | ------------- |  ------------- |  ------------- | 

**_Boutons d'action:_** 

| Bouton | Evènement | Allez vers | Dépendance |
| --- | --- | --- | --- |
| Externalisation | Selectionner le choix "Externalisation" | Rester sur la même page | --- |
| Ingénierie | Selectionner le choix "Ingénierie" | Rester sur la même page | --- |
| Conseil | Selectionner le choix "Conseil" | Rester sur la même page | --- |
| Intégration | Selectionner le choix "Intégration" | Rester sur la même page | --- |
| Opérations et Maintenances | Selectionner le choix "Opérations et Maintenances" | Rester sur la même page | --- |
| Retour au menu | Retourner au menu principale | Rester sur la même page | --- |
| icon "Retour" | Retourner à la liste de choix precédente | Rester sur la même page | --- |

_**Critères d’acceptation:**_ 

Scénario : .

Étant donné que je suis au menu principale,
Lorsque je clique sur "Services" ,
Alors le système affiche 5 choix : "Ingénierie", "Externalisation", "Conseil", "Intégration" et "Opérations et Maintenances" . Chaque choix conduit à un ensemble d'informations **(Mockup 1-2-3-4-5-6)**

> **_Mock up 1_**
![Services](https://user-images.githubusercontent.com/60237898/154445469-160d471b-fec7-49c9-83f8-3252ccc022dd.png)

> **_Mock up 2_**
![Services - Ingénierie](https://user-images.githubusercontent.com/60237898/154445511-03b91e89-2b42-4c95-b642-966e1aa4cc13.png)

> **_Mock up 3_**
![Services - Externalisation](https://user-images.githubusercontent.com/60237898/154445543-e6d5612e-f033-41c4-8283-711dd61219e4.png)

> **_Mock up 4_**
![Services - Conseil](https://user-images.githubusercontent.com/60237898/154445574-7ece3b68-c9b2-460b-9dfd-3f6443bb2687.png)

> **_Mock up 5_**
![Services - Intégration](https://user-images.githubusercontent.com/60237898/154445598-22445b93-df78-4a3f-84d1-a366aabb3ec7.png)

> **_Mock up 6_**
![Services - Opérations   Maintenances](https://user-images.githubusercontent.com/60237898/154445668-e9a02180-edd7-4197-b6f4-033ef968e1a6.png)
