### ISSUE TITLE
Mise en place de l'environnement Django

### ISSUE THREAD

**Issue by achrefsoltani** [achrefsoltani/Trituxchatbot#28]
**_Tâches développeur :_** 

- [x] Création du project Django .

- [x] Configuration de la base de donnée.

- [x] Création des entités .

![v0_classe](https://user-images.githubusercontent.com/60237898/154657909-d1a955ba-1110-45c3-9602-9899bd651513.png)
