### ISSUE TITLE
[Visiteur]Bienvenue

### ISSUE THREAD

**Issue by achrefsoltani** [achrefsoltani/Trituxchatbot#31]
**_Tâches développeur :_** 

- [x] Api : Créer l'api de récupération des choix

- [x] Front : Ouverture et fermeture de l'onglet du dialog du chatbot .

- [x] Front :Affichage de message de bienvenue et du menu de choix principale.

**_Description:_**

En tant que Visiteur, je voudrais être en mesure d'ouvrir le chatbot et intéragir avec lui.

_**Pré-conditions:**_ 

Les choix sont déja crées.

_**Post-conditions:**_ 

Ouverture de l'onglet du message avec un bienvenue et un menu de choix principale.

**_Règles métiers:_**  

| Attribut  | Importance  | Règle  | Priorité  |
| ------------- | ------------- |  ------------- |  ------------- | 

**_Données à afficher  :_**

| N° | Donnée | Type | Description | 
| --- | --- | --- | --- | 
| 1 | Welcome message | Text | message de bienvenue  |
| 2 | Main menu | Text | Liste des choix de base  |

**_Boutons d'action:_** 

| Bouton | Evènement | Allez vers | Dépendance |
| --- | --- | --- | --- |
| Logo | Ouvrir l'onglet de dialogue | Rester sur la même page | - |
| Icon "X" | Cacher l'onglet de dialogue | Rester sur la même page | - |
| Icon "Home" | Réinitialiser le chatbot | Rester sur la même page | - |

_**Critères d’acceptation:**_ 

Scénario : .

Étant donné que je suis sur le site,
Lorsque je clique sur le logo du chatbot ,
Alors le système affiche l'onglet du dialogue avec un message de bienvenue et un menu de choix principales. **(Mockup 1-2)**

> **_Mock up 1_**
![Logo only](https://user-images.githubusercontent.com/60237898/154447677-f243f50e-ca8c-4c22-b204-4afc6ce58ef5.png)

> **_Mock up 2_**
![Main Menu](https://user-images.githubusercontent.com/60237898/154447704-3abbc3a6-5cdc-4bed-82dd-eef8b7d8fab6.png)
