### ISSUE TITLE
[Visiteur]Solutions

### ISSUE THREAD

**Issue by achrefsoltani** [achrefsoltani/Trituxchatbot#4]
**_Tâches développeur :_** 

- [x] Api : Créer l'api de récupération des choix

- [x] Front : Affiche le choix de l'utilisateur dans le chatbot .

- [x] Front : Afficher les réponses.

**_Description:_**

En tant que Visiteur, je voudrais être en mesure d'interagir avec le chatbot afin de pouvoir avoir une idée sur les solutions du Groupe Tritux.

_**Pré-conditions:**_ 

Les choix sont déja crées.
On a choisi "Solutions".

_**Post-conditions:**_ 

Affichage des choix et réponses.

**_Règles métiers:_**  

| Attribut  | Importance  | Règle  | Priorité  |
| ------------- | ------------- |  ------------- |  ------------- | 

**_Boutons d'action:_** 

| Bouton | Evènement | Allez vers | Dépendance |
| --- | --- | --- | --- |
| Retour au menu | Retourner au menu principale | Rester sur la même page | --- |
| icon "Retour" | Retourner à la liste de choix precédente | Rester sur la même page | --- |

_**Critères d’acceptation:**_ 

Scénario : .

Étant donné que je suis au menu principale,
Lorsque je clique sur "Solutions" ,
Alors le système affiche une description des solutions du Groupe Tritux . **(Mockup 1)**

> **_Mock up 1_**
![Solutions](https://user-images.githubusercontent.com/60237898/154446408-6a9a737a-e2d8-4810-9d29-1f6819ddb5a8.png)
